# Generated by Django 2.1.2 on 2018-10-03 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('tipo_conta', models.CharField(max_length=30)),
                ('saldo_conta', models.FloatField()),
                ('usaurio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=255)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('data_vencimento', models.DateTimeField()),
                ('data_pagamento', models.DateTimeField()),
                ('tipo_fatura', models.CharField(max_length=1)),
                ('valor_fatura', models.FloatField()),
                ('valor_pago', models.FloatField()),
                ('desconto', models.FloatField()),
                ('juro', models.FloatField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
