# Generated by Django 2.1.2 on 2018-10-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='valor_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='desconto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='juro',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_fatura',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_pago',
            field=models.FloatField(default=0),
        ),
    ]
