# Generated by Django 2.1.2 on 2018-10-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20181003_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='tipo_fatura',
            field=models.CharField(choices=[('P', 'Pagar'), ('R', 'Receber')], max_length=1),
        ),
    ]
